version: '3'
services:
    spark:
      image: bitnami/spark:2.4.4
      ports:
        - "8080:8080"
        - "7077:7077"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/"]
        interval: 3s
        timeout: 3s
        retries: 3
    emr:
      build: .
      ports:
        - "3000:3000"
      volumes:
        - ./src:/home/app/src
        - ./test:/home/app/test
        - ~/.aws:/root/.aws
    livy:
      image: cloudiator/livy-server:melodic-stable
      depends_on:
        - spark
      ports:
        - "8998:8998"
      environment:
        - SPARK_MASTER_ENDPOINT=spark
        - SPARK_MASTER_PORT=7077
        - DEPLOY_MODE=client
      volumes:
      - /tmp:/tmp

        
